name: Workflow deploiement d'un Host Pool WVD
on:
  push:
    branches: [master]
    paths:
    - "Spring2020/ARM/**"

jobs:
  build-and-deploy:
    name: deploiement dans Azure
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login Az Cli
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script Creation d'un "Resource Group"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.9.0
        inlineScript: |
          az group create --name RG-WVD-Hosts --location eastus2

    - name: Git - Recupération des sources
      uses: actions/checkout@master

    - name: Azure - Login ARM
      uses: Azure/github-actions/login@master
      env:
        AZURE_SUBSCRIPTION: "Services de la plateforme Windows Azure pour Visual Studio Ultim"
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}

    - name: Azure - Deploy ARM Template
      uses: Azure/github-actions/arm@master
      env:
        AZURE_RESOURCE_GROUP: RG-WVD-Hosts
        AZURE_TEMPLATE_LOCATION: ./Spring/ARM/azuredeploy.json
        AZURE_TEMPLATE_PARAM_LOCATION: ./Spring/ARM/azuredeploy.parameters.json
        
